//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CharacterId&quot;: -4,
        ///    &quot;Name&quot;: &quot;all-characters-amplified&quot;,
        ///    &quot;DisplayName&quot;: &quot;All Characters (Amplified)&quot;
        ///  },
        ///  {
        ///    &quot;CharacterId&quot;: -3,
        ///    &quot;Name&quot;: &quot;all-characters&quot;,
        ///    &quot;DisplayName&quot;: &quot;All Characters&quot;
        ///  },
        ///  {
        ///    &quot;CharacterId&quot;: -2,
        ///    &quot;Name&quot;: &quot;story-mode&quot;,
        ///    &quot;DisplayName&quot;: &quot;Story Mode&quot;
        ///  },
        ///  {
        ///    &quot;CharacterId&quot;: 0,
        ///    &quot;Name&quot;: &quot;cadence&quot;,
        ///    &quot;DisplayName&quot;: &quot;Cadence&quot;
        ///  },
        ///  {
        ///    &quot;CharacterId&quot;: 1,
        ///    &quot;Name&quot;: &quot;melody&quot;,
        ///    &quot;DisplayName&quot;: &quot;Melody&quot;
        ///  },
        ///  {
        ///    &quot;Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;LeaderboardId&quot;: 391760,
        ///    &quot;DisplayName&quot;: &quot;Daily (2014-07-30) (Early Access)&quot;,
        ///    &quot;Name&quot;: &quot;30/7/2014&quot;,
        ///    &quot;IsProduction&quot;: false,
        ///    &quot;ProductId&quot;: 0,
        ///    &quot;Date&quot;: &quot;2014-07-30T00:00:00Z&quot;
        ///  },
        ///  {
        ///    &quot;LeaderboardId&quot;: 394529,
        ///    &quot;DisplayName&quot;: &quot;Daily (2014-07-31) (Early Access)&quot;,
        ///    &quot;Name&quot;: &quot;31/7/2014&quot;,
        ///    &quot;IsProduction&quot;: false,
        ///    &quot;ProductId&quot;: 0,
        ///    &quot;Date&quot;: &quot;2014-07-31T00:00:00Z&quot;
        ///  },
        ///  {
        ///    &quot;LeaderboardId&quot;: 396523,
        ///    &quot;DisplayName&quot;: &quot;Daily (2014-08-01) (Early Access)&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DailyLeaderboards {
            get {
                return ResourceManager.GetString("DailyLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;LeaderboardId&quot;: 693094,
        ///    &quot;DisplayName&quot;: &quot;All Characters Score&quot;,
        ///    &quot;Name&quot;: &quot;HARDCORE All Chars&quot;,
        ///    &quot;IsProduction&quot;: false,
        ///    &quot;ProductId&quot;: 0,
        ///    &quot;ModeId&quot;: 0,
        ///    &quot;RunId&quot;: 0,
        ///    &quot;CharacterId&quot;: -3,
        ///    &quot;IsCustomMusic&quot;: false,
        ///    &quot;IsCoOp&quot;: false
        ///  },
        ///  {
        ///    &quot;LeaderboardId&quot;: 685490,
        ///    &quot;DisplayName&quot;: &quot;All Characters Score (Custom Music)&quot;,
        ///    &quot;Name&quot;: &quot;HARDCORE All Chars CUSTOM MUSIC&quot;,
        ///    &quot;IsProduction&quot;: false,
        ///    &quot;ProductId&quot;: 0,
        ///    &quot;ModeId&quot;: 0,
        ///    &quot;RunId&quot;: 0,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaderboards {
            get {
                return ResourceManager.GetString("Leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ModeId&quot;: 0,
        ///    &quot;Name&quot;: &quot;standard&quot;,
        ///    &quot;DisplayName&quot;: &quot;Standard&quot;
        ///  },
        ///  {
        ///    &quot;ModeId&quot;: 1,
        ///    &quot;Name&quot;: &quot;no-return&quot;,
        ///    &quot;DisplayName&quot;: &quot;No Return&quot;
        ///  },
        ///  {
        ///    &quot;ModeId&quot;: 2,
        ///    &quot;Name&quot;: &quot;hard&quot;,
        ///    &quot;DisplayName&quot;: &quot;Hard&quot;
        ///  },
        ///  {
        ///    &quot;ModeId&quot;: 3,
        ///    &quot;Name&quot;: &quot;phasing&quot;,
        ///    &quot;DisplayName&quot;: &quot;Phasing&quot;
        ///  },
        ///  {
        ///    &quot;ModeId&quot;: 4,
        ///    &quot;Name&quot;: &quot;randomizer&quot;,
        ///    &quot;DisplayName&quot;: &quot;Randomizer&quot;
        ///  },
        ///  {
        ///    &quot;ModeId&quot;: 5,
        ///    &quot;Name&quot;: &quot;mystery&quot;,
        ///    &quot;DisplayName&quot;: &quot;Mystery&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Modes {
            get {
                return ResourceManager.GetString("Modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ProductId&quot;: 0,
        ///    &quot;Name&quot;: &quot;classic&quot;,
        ///    &quot;DisplayName&quot;: &quot;Classic&quot;
        ///  },
        ///  {
        ///    &quot;ProductId&quot;: 1,
        ///    &quot;Name&quot;: &quot;amplified&quot;,
        ///    &quot;DisplayName&quot;: &quot;Amplified&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;RunId&quot;: 0,
        ///    &quot;Name&quot;: &quot;score&quot;,
        ///    &quot;DisplayName&quot;: &quot;Score&quot;
        ///  },
        ///  {
        ///    &quot;RunId&quot;: 1,
        ///    &quot;Name&quot;: &quot;speed&quot;,
        ///    &quot;DisplayName&quot;: &quot;Speed&quot;
        ///  },
        ///  {
        ///    &quot;RunId&quot;: 2,
        ///    &quot;Name&quot;: &quot;seeded-score&quot;,
        ///    &quot;DisplayName&quot;: &quot;Seeded Score&quot;
        ///  },
        ///  {
        ///    &quot;RunId&quot;: 3,
        ///    &quot;Name&quot;: &quot;seeded-speed&quot;,
        ///    &quot;DisplayName&quot;: &quot;Seeded Speed&quot;
        ///  },
        ///  {
        ///    &quot;RunId&quot;: 4,
        ///    &quot;Name&quot;: &quot;deathless&quot;,
        ///    &quot;DisplayName&quot;: &quot;Deathless&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Runs {
            get {
                return ResourceManager.GetString("Runs", resourceCulture);
            }
        }
    }
}
